# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lukasg/dem/DEM-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lukasg/dem/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukasg/dem/build/CMakeFiles /home/lukasg/dem/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukasg/dem/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulator_multi_gpu

# Build rule for target.
simulator_multi_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulator_multi_gpu
.PHONY : simulator_multi_gpu

# fast build rule for target.
simulator_multi_gpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator_multi_gpu.dir/build.make CMakeFiles/simulator_multi_gpu.dir/build
.PHONY : simulator_multi_gpu/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core.dir/build.make src/core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named DEMERuntimeDataHelper

# Build rule for target.
DEMERuntimeDataHelper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMERuntimeDataHelper
.PHONY : DEMERuntimeDataHelper

# fast build rule for target.
DEMERuntimeDataHelper/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/DEMERuntimeDataHelper.dir/build.make src/core/CMakeFiles/DEMERuntimeDataHelper.dir/build
.PHONY : DEMERuntimeDataHelper/fast

#=============================================================================
# Target rules for targets named DEMERuntimeDataHelper_install

# Build rule for target.
DEMERuntimeDataHelper_install: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMERuntimeDataHelper_install
.PHONY : DEMERuntimeDataHelper_install

# fast build rule for target.
DEMERuntimeDataHelper_install/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/DEMERuntimeDataHelper_install.dir/build.make src/core/CMakeFiles/DEMERuntimeDataHelper_install.dir/build
.PHONY : DEMERuntimeDataHelper_install/fast

#=============================================================================
# Target rules for targets named DEM

# Build rule for target.
DEM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEM
.PHONY : DEM

# fast build rule for target.
DEM/fast:
	$(MAKE) $(MAKESILENT) -f src/DEM/CMakeFiles/DEM.dir/build.make src/DEM/CMakeFiles/DEM.dir/build
.PHONY : DEM/fast

#=============================================================================
# Target rules for targets named algorithms

# Build rule for target.
algorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algorithms
.PHONY : algorithms

# fast build rule for target.
algorithms/fast:
	$(MAKE) $(MAKESILENT) -f src/algorithms/CMakeFiles/algorithms.dir/build.make src/algorithms/CMakeFiles/algorithms.dir/build
.PHONY : algorithms/fast

#=============================================================================
# Target rules for targets named DEMdemo_Repose

# Build rule for target.
DEMdemo_Repose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Repose
.PHONY : DEMdemo_Repose

# fast build rule for target.
DEMdemo_Repose/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Repose.dir/build.make src/demo/CMakeFiles/DEMdemo_Repose.dir/build
.PHONY : DEMdemo_Repose/fast

#=============================================================================
# Target rules for targets named DEMdemo_Repose2D

# Build rule for target.
DEMdemo_Repose2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Repose2D
.PHONY : DEMdemo_Repose2D

# fast build rule for target.
DEMdemo_Repose2D/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Repose2D.dir/build.make src/demo/CMakeFiles/DEMdemo_Repose2D.dir/build
.PHONY : DEMdemo_Repose2D/fast

#=============================================================================
# Target rules for targets named DEMdemo_ContactChain

# Build rule for target.
DEMdemo_ContactChain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_ContactChain
.PHONY : DEMdemo_ContactChain

# fast build rule for target.
DEMdemo_ContactChain/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_ContactChain.dir/build.make src/demo/CMakeFiles/DEMdemo_ContactChain.dir/build
.PHONY : DEMdemo_ContactChain/fast

#=============================================================================
# Target rules for targets named DEMdemo_Plow

# Build rule for target.
DEMdemo_Plow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Plow
.PHONY : DEMdemo_Plow

# fast build rule for target.
DEMdemo_Plow/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Plow.dir/build.make src/demo/CMakeFiles/DEMdemo_Plow.dir/build
.PHONY : DEMdemo_Plow/fast

#=============================================================================
# Target rules for targets named DEMdemo_Sieve

# Build rule for target.
DEMdemo_Sieve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Sieve
.PHONY : DEMdemo_Sieve

# fast build rule for target.
DEMdemo_Sieve/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Sieve.dir/build.make src/demo/CMakeFiles/DEMdemo_Sieve.dir/build
.PHONY : DEMdemo_Sieve/fast

#=============================================================================
# Target rules for targets named DEMdemo_SingleSphereCollide

# Build rule for target.
DEMdemo_SingleSphereCollide: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_SingleSphereCollide
.PHONY : DEMdemo_SingleSphereCollide

# fast build rule for target.
DEMdemo_SingleSphereCollide/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_SingleSphereCollide.dir/build.make src/demo/CMakeFiles/DEMdemo_SingleSphereCollide.dir/build
.PHONY : DEMdemo_SingleSphereCollide/fast

#=============================================================================
# Target rules for targets named DEMdemo_TestPack

# Build rule for target.
DEMdemo_TestPack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_TestPack
.PHONY : DEMdemo_TestPack

# fast build rule for target.
DEMdemo_TestPack/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_TestPack.dir/build.make src/demo/CMakeFiles/DEMdemo_TestPack.dir/build
.PHONY : DEMdemo_TestPack/fast

#=============================================================================
# Target rules for targets named DEMdemo_RotatingDrum

# Build rule for target.
DEMdemo_RotatingDrum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_RotatingDrum
.PHONY : DEMdemo_RotatingDrum

# fast build rule for target.
DEMdemo_RotatingDrum/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_RotatingDrum.dir/build.make src/demo/CMakeFiles/DEMdemo_RotatingDrum.dir/build
.PHONY : DEMdemo_RotatingDrum/fast

#=============================================================================
# Target rules for targets named DEMdemo_Centrifuge

# Build rule for target.
DEMdemo_Centrifuge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Centrifuge
.PHONY : DEMdemo_Centrifuge

# fast build rule for target.
DEMdemo_Centrifuge/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Centrifuge.dir/build.make src/demo/CMakeFiles/DEMdemo_Centrifuge.dir/build
.PHONY : DEMdemo_Centrifuge/fast

#=============================================================================
# Target rules for targets named DEMdemo_GameOfLife

# Build rule for target.
DEMdemo_GameOfLife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_GameOfLife
.PHONY : DEMdemo_GameOfLife

# fast build rule for target.
DEMdemo_GameOfLife/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_GameOfLife.dir/build.make src/demo/CMakeFiles/DEMdemo_GameOfLife.dir/build
.PHONY : DEMdemo_GameOfLife/fast

#=============================================================================
# Target rules for targets named DEMdemo_BallDrop

# Build rule for target.
DEMdemo_BallDrop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_BallDrop
.PHONY : DEMdemo_BallDrop

# fast build rule for target.
DEMdemo_BallDrop/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_BallDrop.dir/build.make src/demo/CMakeFiles/DEMdemo_BallDrop.dir/build
.PHONY : DEMdemo_BallDrop/fast

#=============================================================================
# Target rules for targets named DEMdemo_BallDrop2D

# Build rule for target.
DEMdemo_BallDrop2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_BallDrop2D
.PHONY : DEMdemo_BallDrop2D

# fast build rule for target.
DEMdemo_BallDrop2D/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_BallDrop2D.dir/build.make src/demo/CMakeFiles/DEMdemo_BallDrop2D.dir/build
.PHONY : DEMdemo_BallDrop2D/fast

#=============================================================================
# Target rules for targets named DEMdemo_Mixer

# Build rule for target.
DEMdemo_Mixer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Mixer
.PHONY : DEMdemo_Mixer

# fast build rule for target.
DEMdemo_Mixer/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Mixer.dir/build.make src/demo/CMakeFiles/DEMdemo_Mixer.dir/build
.PHONY : DEMdemo_Mixer/fast

#=============================================================================
# Target rules for targets named DEMdemo_GRCPrep_Part1

# Build rule for target.
DEMdemo_GRCPrep_Part1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_GRCPrep_Part1
.PHONY : DEMdemo_GRCPrep_Part1

# fast build rule for target.
DEMdemo_GRCPrep_Part1/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_GRCPrep_Part1.dir/build.make src/demo/CMakeFiles/DEMdemo_GRCPrep_Part1.dir/build
.PHONY : DEMdemo_GRCPrep_Part1/fast

#=============================================================================
# Target rules for targets named DEMdemo_GRCPrep_Part2

# Build rule for target.
DEMdemo_GRCPrep_Part2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_GRCPrep_Part2
.PHONY : DEMdemo_GRCPrep_Part2

# fast build rule for target.
DEMdemo_GRCPrep_Part2/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_GRCPrep_Part2.dir/build.make src/demo/CMakeFiles/DEMdemo_GRCPrep_Part2.dir/build
.PHONY : DEMdemo_GRCPrep_Part2/fast

#=============================================================================
# Target rules for targets named DEMdemo_GRCPrep_Part3

# Build rule for target.
DEMdemo_GRCPrep_Part3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_GRCPrep_Part3
.PHONY : DEMdemo_GRCPrep_Part3

# fast build rule for target.
DEMdemo_GRCPrep_Part3/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_GRCPrep_Part3.dir/build.make src/demo/CMakeFiles/DEMdemo_GRCPrep_Part3.dir/build
.PHONY : DEMdemo_GRCPrep_Part3/fast

#=============================================================================
# Target rules for targets named DEMdemo_ConePenetration

# Build rule for target.
DEMdemo_ConePenetration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_ConePenetration
.PHONY : DEMdemo_ConePenetration

# fast build rule for target.
DEMdemo_ConePenetration/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_ConePenetration.dir/build.make src/demo/CMakeFiles/DEMdemo_ConePenetration.dir/build
.PHONY : DEMdemo_ConePenetration/fast

#=============================================================================
# Target rules for targets named DEMdemo_Shake

# Build rule for target.
DEMdemo_Shake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Shake
.PHONY : DEMdemo_Shake

# fast build rule for target.
DEMdemo_Shake/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Shake.dir/build.make src/demo/CMakeFiles/DEMdemo_Shake.dir/build
.PHONY : DEMdemo_Shake/fast

#=============================================================================
# Target rules for targets named DEMdemo_WheelDP

# Build rule for target.
DEMdemo_WheelDP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_WheelDP
.PHONY : DEMdemo_WheelDP

# fast build rule for target.
DEMdemo_WheelDP/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_WheelDP.dir/build.make src/demo/CMakeFiles/DEMdemo_WheelDP.dir/build
.PHONY : DEMdemo_WheelDP/fast

#=============================================================================
# Target rules for targets named DEMdemo_WheelDPSimplified

# Build rule for target.
DEMdemo_WheelDPSimplified: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_WheelDPSimplified
.PHONY : DEMdemo_WheelDPSimplified

# fast build rule for target.
DEMdemo_WheelDPSimplified/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_WheelDPSimplified.dir/build.make src/demo/CMakeFiles/DEMdemo_WheelDPSimplified.dir/build
.PHONY : DEMdemo_WheelDPSimplified/fast

#=============================================================================
# Target rules for targets named DEMdemo_WheelSlopeSlip

# Build rule for target.
DEMdemo_WheelSlopeSlip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_WheelSlopeSlip
.PHONY : DEMdemo_WheelSlopeSlip

# fast build rule for target.
DEMdemo_WheelSlopeSlip/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_WheelSlopeSlip.dir/build.make src/demo/CMakeFiles/DEMdemo_WheelSlopeSlip.dir/build
.PHONY : DEMdemo_WheelSlopeSlip/fast

#=============================================================================
# Target rules for targets named DEMdemo_Indentation

# Build rule for target.
DEMdemo_Indentation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Indentation
.PHONY : DEMdemo_Indentation

# fast build rule for target.
DEMdemo_Indentation/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Indentation.dir/build.make src/demo/CMakeFiles/DEMdemo_Indentation.dir/build
.PHONY : DEMdemo_Indentation/fast

#=============================================================================
# Target rules for targets named DEMdemo_SolarSystem

# Build rule for target.
DEMdemo_SolarSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_SolarSystem
.PHONY : DEMdemo_SolarSystem

# fast build rule for target.
DEMdemo_SolarSystem/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_SolarSystem.dir/build.make src/demo/CMakeFiles/DEMdemo_SolarSystem.dir/build
.PHONY : DEMdemo_SolarSystem/fast

#=============================================================================
# Target rules for targets named DEMdemo_Electrostatic

# Build rule for target.
DEMdemo_Electrostatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Electrostatic
.PHONY : DEMdemo_Electrostatic

# fast build rule for target.
DEMdemo_Electrostatic/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Electrostatic.dir/build.make src/demo/CMakeFiles/DEMdemo_Electrostatic.dir/build
.PHONY : DEMdemo_Electrostatic/fast

#=============================================================================
# Target rules for targets named DEMdemo_FlexibleMesh

# Build rule for target.
DEMdemo_FlexibleMesh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_FlexibleMesh
.PHONY : DEMdemo_FlexibleMesh

# fast build rule for target.
DEMdemo_FlexibleMesh/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_FlexibleMesh.dir/build.make src/demo/CMakeFiles/DEMdemo_FlexibleMesh.dir/build
.PHONY : DEMdemo_FlexibleMesh/fast

#=============================================================================
# Target rules for targets named DEMdemo_Hopper_Sphere_Cylinder

# Build rule for target.
DEMdemo_Hopper_Sphere_Cylinder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Hopper_Sphere_Cylinder
.PHONY : DEMdemo_Hopper_Sphere_Cylinder

# fast build rule for target.
DEMdemo_Hopper_Sphere_Cylinder/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Hopper_Sphere_Cylinder.dir/build.make src/demo/CMakeFiles/DEMdemo_Hopper_Sphere_Cylinder.dir/build
.PHONY : DEMdemo_Hopper_Sphere_Cylinder/fast

#=============================================================================
# Target rules for targets named DEMdemo_Fracture_Box

# Build rule for target.
DEMdemo_Fracture_Box: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEMdemo_Fracture_Box
.PHONY : DEMdemo_Fracture_Box

# fast build rule for target.
DEMdemo_Fracture_Box/fast:
	$(MAKE) $(MAKESILENT) -f src/demo/CMakeFiles/DEMdemo_Fracture_Box.dir/build.make src/demo/CMakeFiles/DEMdemo_Fracture_Box.dir/build
.PHONY : DEMdemo_Fracture_Box/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... DEM"
	@echo "... DEMERuntimeDataHelper"
	@echo "... DEMERuntimeDataHelper_install"
	@echo "... DEMdemo_BallDrop"
	@echo "... DEMdemo_BallDrop2D"
	@echo "... DEMdemo_Centrifuge"
	@echo "... DEMdemo_ConePenetration"
	@echo "... DEMdemo_ContactChain"
	@echo "... DEMdemo_Electrostatic"
	@echo "... DEMdemo_FlexibleMesh"
	@echo "... DEMdemo_Fracture_Box"
	@echo "... DEMdemo_GRCPrep_Part1"
	@echo "... DEMdemo_GRCPrep_Part2"
	@echo "... DEMdemo_GRCPrep_Part3"
	@echo "... DEMdemo_GameOfLife"
	@echo "... DEMdemo_Hopper_Sphere_Cylinder"
	@echo "... DEMdemo_Indentation"
	@echo "... DEMdemo_Mixer"
	@echo "... DEMdemo_Plow"
	@echo "... DEMdemo_Repose"
	@echo "... DEMdemo_Repose2D"
	@echo "... DEMdemo_RotatingDrum"
	@echo "... DEMdemo_Shake"
	@echo "... DEMdemo_Sieve"
	@echo "... DEMdemo_SingleSphereCollide"
	@echo "... DEMdemo_SolarSystem"
	@echo "... DEMdemo_TestPack"
	@echo "... DEMdemo_WheelDP"
	@echo "... DEMdemo_WheelDPSimplified"
	@echo "... DEMdemo_WheelSlopeSlip"
	@echo "... algorithms"
	@echo "... core"
	@echo "... simulator_multi_gpu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

